spring:
  application:
    name: ms-gateway-service
server:
  port: 8888
  cloud:
    discovery:
      enabled: true
  gateway:
    routes:
      - id: r1
        uri: http://localhost:8000/
        predicates:
            - Path=/customers/**

      - id: r2
        uri: http://localhost:8100/
        predicates:
          - Path=/accounts/**

